name: End-to-End Tests
on:
  push:
    branches:
      - main
      - master
  pull_request:
  # schedule:
  #   - cron: "0 0 * * 0"
jobs:
  e2e-test:
    name: E2E Test Python ${{ matrix.py }} - Postgis ${{ matrix.postgis }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.12"
        postgis:
          - "latest"
    services:
      geoserver:
        image: docker.osgeo.org/geoserver:2.27.0
        env:
          SKIP_DEMO_DATA: false
          CORS_ENABLED: true
          ENABLE_JSONP: true
        ports:
          - 8181:8080
      postgis:
        image: postgis/postgis:${{ matrix.postgis }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.py }} for test
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install tox tox-gh-actions
      - name: Setup Postgis
        run: |
          PGPASSWORD=mysecretpassword psql -U postgres -h localhost -c "CREATE DATABASE tds_tests WITH OWNER postgres;"
          PGPASSWORD=mysecretpassword psql -U postgres -h localhost -d tds_tests -c  "CREATE EXTENSION postgis;"
          if [[ ${{ matrix.postgis }} == *"3.4-alpine"* ]]; then PGPASSWORD=mysecretpassword psql -U postgres -h localhost -d tds_tests -c  "CREATE EXTENSION postgis_raster;"; fi
          sleep 10
      - name: Run tests
        run: tox -e e2e_gs_tests
