name: Publish to PyPI

on:
  push:
    tags:
      - '*.*.*'  # Triggers on version tags like 2.4.0, 1.0.0, etc.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for trusted publishing
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for setuptools_scm
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools_scm[toml]
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # Using trusted publishing (recommended)
        # No API token needed if trusted publishing is configured
        # Otherwise, add PYPI_API_TOKEN to repository secrets
        password: ${{ secrets.PYPI_API_TOKEN }}
